apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: job-api
  namespace: d4-jobs
  labels:
    app.kubernetes.io/name: job-api
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: job-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: job-api
                port:
                  number: 8090
